services:
  app:
    build:
      context: ./services/app
      target: app
    image: ${DOCKERHUB_USER}/simple-app:${IMAGE_TAG}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - TZ=${TZ}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
<<<<<<< Updated upstream
=======
      # # HTTP -> redirect to HTTPS
      # - "traefik.http.routers.app.rule=Host(`${DOMAIN}`)"
      # - "traefik.http.routers.app.entrypoints=web"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.routers.app.middlewares=redirect-to-https"
>>>>>>> Stashed changes
      # HTTPS router
      - "traefik.http.routers.app-secure.rule=Host(`myapp.${DOMAIN}`)"
      - "traefik.http.routers.app-secure.entrypoints=websecure"
<<<<<<< Updated upstream
      - "traefik.http.routers.app-secure.tls=true"
      - "traefik.http.routers.app-secure.tls.certresolver=myresolver"
=======
      # - "traefik.http.routers.app-secure.tls=true"
      - "traefik.http.routers.app-secure.tls.certresolver=mytlschallenge"
      # Point Traefik to the app's internal port
>>>>>>> Stashed changes
      - "traefik.http.services.app-secure.loadbalancer.server.port=8000"
    restart: unless-stopped
    networks:
      - appnet

  db:
    build:
      context: ./services/db
      target: db
    image: ${DOCKERHUB_USER}/simple-db:${IMAGE_TAG}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - appnet

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
<<<<<<< Updated upstream
=======
      # - "--entrypoints.web.address=:80"
>>>>>>> Stashed changes
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.service=api@internal"
    restart: unless-stopped
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
<<<<<<< Updated upstream
    driver: bridge
=======
>>>>>>> Stashed changes
